export const countryCodesToNames = {
  "+1": { name: "United States", code: "US" },
  "+7": { name: "Russia", code: "RU" },
  "+33": { name: "France", code: "FR" },
  "+44": { name: "United Kingdom", code: "GB" },
  "+49": { name: "Germany", code: "DE" },
  "+81": { name: "Japan", code: "JP" },
  "+86": { name: "China", code: "CN" },
  "+91": { name: "India", code: "IN" },
  "+353": { name: "Ireland", code: "IE" },
  "+355": { name: "Albania", code: "AL" },
  "+213": { name: "Algeria", code: "DZ" },
  "+376": { name: "Andorra", code: "AD" },
  "+244": { name: "Angola", code: "AO" },
  "+672": { name: "Australian Antarctic Territory", code: "AQ" },
  "+54": { name: "Argentina", code: "AR" },
  "+61": { name: "Australia", code: "AU" },
  "+43": { name: "Austria", code: "AT" },
  "+994": { name: "Azerbaijan", code: "AZ" },
  "+973": { name: "Bahrain", code: "BH" },
  "+880": { name: "Bangladesh", code: "BD" },
  "+375": { name: "Belarus", code: "BY" },
  "+32": { name: "Belgium", code: "BE" },
  "+501": { name: "Belize", code: "BZ" },
  "+229": { name: "Benin", code: "BJ" },
  "+975": { name: "Bhutan", code: "BT" },
  "+591": { name: "Bolivia", code: "BO" },
  "+387": { name: "Bosnia and Herzegovina", code: "BA" },
  "+267": { name: "Botswana", code: "BW" },
  "+55": { name: "Brazil", code: "BR" },
  "+673": { name: "Brunei Darussalam", code: "BN" },
  "+359": { name: "Bulgaria", code: "BG" },
  "+226": { name: "Burkina Faso", code: "BF" },
  "+257": { name: "Burundi", code: "BI" },
  "+855": { name: "Cambodia", code: "KH" },
  "+237": { name: "Cameroon", code: "CM" },
  "+238": { name: "Cape Verde", code: "CV" },
  "+236": { name: "Central African Republic", code: "CF" },
  "+235": { name: "Chad", code: "TD" },
  "+56": { name: "Chile", code: "CL" },
  "+57": { name: "Colombia", code: "CO" },
  "+269": { name: "Comoros", code: "KM" },
  "+243": { name: "Democratic Republic of the Congo", code: "CD" },
  "+242": { name: "Republic of the Congo", code: "CG" },
  "+506": { name: "Costa Rica", code: "CR" },
  "+385": { name: "Croatia", code: "HR" },
  "+53": { name: "Cuba", code: "CU" },
  "+357": { name: "Cyprus", code: "CY" },
  "+420": { name: "Czech Republic", code: "CZ" },
  "+45": { name: "Denmark", code: "DK" },
  "+253": { name: "Djibouti", code: "DJ" },
  "+670": { name: "East Timor", code: "TL" },
  "+593": { name: "Ecuador", code: "EC" },
  "+20": { name: "Egypt", code: "EG" },
  "+503": { name: "El Salvador", code: "SV" },
  "+240": { name: "Equatorial Guinea", code: "GQ" },
  "+291": { name: "Eritrea", code: "ER" },
  "+372": { name: "Estonia", code: "EE" },
  "+251": { name: "Ethiopia", code: "ET" },
  "+298": { name: "Faroe Islands", code: "FO" },
  "+679": { name: "Fiji", code: "FJ" },
  "+358": { name: "Finland", code: "FI" },
  "+691": { name: "Federated States of Micronesia", code: "FM" },
  "+241": { name: "Gabon", code: "GA" },
  "+220": { name: "Gambia", code: "GM" },
  "+995": { name: "Georgia", code: "GE" },
  "+233": { name: "Ghana", code: "GH" },
  "+350": { name: "Gibraltar", code: "GI" },
  "+30": { name: "Greece", code: "GR" },
  "+299": { name: "Greenland", code: "GL" },
  "+590": { name: "Guadeloupe", code: "GP" },
  "+671": { name: "Guam", code: "GU" },
  "+502": { name: "Guatemala", code: "GT" },
  "+224": { name: "Guinea", code: "GN" },
  "+245": { name: "Guinea-Bissau", code: "GW" },
  "+592": { name: "Guyana", code: "GY" },
  "+509": { name: "Haiti", code: "HT" },
  "+504": { name: "Honduras", code: "HN" },
  "+852": { name: "Hong Kong", code: "HK" },
  "+36": { name: "Hungary", code: "HU" },
  "+354": { name: "Iceland", code: "IS" },
  "+62": { name: "Indonesia", code: "ID" },
  "+98": { name: "Iran", code: "IR" },
  "+964": { name: "Iraq", code: "IQ" },
  "+972": { name: "Israel", code: "IL" },
  "+39": { name: "Italy", code: "IT" },
  "+225": { name: "Ivory Coast", code: "CI" },
  "+962": { name: "Jordan", code: "JO" },
  "+254": { name: "Kenya", code: "KE" },
  "+686": { name: "Kiribati", code: "KI" },
  "+965": { name: "Kuwait", code: "KW" },
  "+996": { name: "Kyrgyzstan", code: "KG" },
  "+856": { name: "Laos", code: "LA" },
  "+371": { name: "Latvia", code: "LV" },
  "+961": { name: "Lebanon", code: "LB" },
  "+266": { name: "Lesotho", code: "LS" },
  "+231": { name: "Liberia", code: "LR" },
  "+218": { name: "Libya", code: "LY" },
  "+423": { name: "Liechtenstein", code: "LI" },
  "+370": { name: "Lithuania", code: "LT" },
  "+352": { name: "Luxembourg", code: "LU" },
  "+853": { name: "Macau", code: "MO" },
  "+389": { name: "North Macedonia", code: "MK" },
  "+261": { name: "Madagascar", code: "MG" },
  "+265": { name: "Malawi", code: "MW" },
  "+60": { name: "Malaysia", code: "MY" },
  "+960": { name: "Maldives", code: "MV" },
  "+223": { name: "Mali", code: "ML" },
  "+356": { name: "Malta", code: "MT" },
  "+692": { name: "Marshall Islands", code: "MH" },
  "+596": { name: "Martinique", code: "MQ" },
  "+222": { name: "Mauritania", code: "MR" },
  "+230": { name: "Mauritius", code: "MU" },
  "+262": { name: "Mayotte", code: "YT" },
  "+52": { name: "Mexico", code: "MX" },
  "+373": { name: "Moldova", code: "MD" },
  "+377": { name: "Monaco", code: "MC" },
  "+976": { name: "Mongolia", code: "MN" },
  "+382": { name: "Montenegro", code: "ME" },
  "+212": { name: "Morocco", code: "MA" },
  "+258": { name: "Mozambique", code: "MZ" },
  "+95": { name: "Myanmar", code: "MM" },
  "+264": { name: "Namibia", code: "NA" },
  "+674": { name: "Nauru", code: "NR" },
  "+977": { name: "Nepal", code: "NP" },
  "+31": { name: "Netherlands", code: "NL" },
  "+599": { name: "Netherlands Antilles", code: "AN" },
  "+687": { name: "New Caledonia", code: "NC" },
  "+64": { name: "New Zealand", code: "NZ" },
  "+505": { name: "Nicaragua", code: "NI" },
  "+227": { name: "Niger", code: "NE" },
  "+234": { name: "Nigeria", code: "NG" },
  "+683": { name: "Niue", code: "NU" },
  "+47": { name: "Norway", code: "NO" },
  "+968": { name: "Oman", code: "OM" },
  "+92": { name: "Pakistan", code: "PK" },
  "+680": { name: "Palau", code: "PW" },
  "+970": { name: "Palestinian territories", code: "PS" },
  "+507": { name: "Panama", code: "PA" },
  "+675": { name: "Papua New Guinea", code: "PG" },
  "+595": { name: "Paraguay", code: "PY" },
  "+51": { name: "Peru", code: "PE" },
  "+63": { name: "Philippines", code: "PH" },
  "+48": { name: "Poland", code: "PL" },
  "+351": { name: "Portugal", code: "PT" },
  "+974": { name: "Qatar", code: "QA" },
  "+250": { name: "Rwanda", code: "RW" },
  "+290": { name: "Saint Helena", code: "SH" },
  "+508": { name: "Saint Pierre and Miquelon", code: "PM" },
  "+685": { name: "Samoa", code: "WS" },
  "+378": { name: "San Marino", code: "SM" },
  "+239": { name: "São Tomé and Príncipe", code: "ST" },
  "+966": { name: "Saudi Arabia", code: "SA" },
  "+221": { name: "Senegal", code: "SN" },
  "+381": { name: "Serbia", code: "RS" },
  "+248": { name: "Seychelles", code: "SC" },
  "+232": { name: "Sierra Leone", code: "SL" },
  "+65": { name: "Singapore", code: "SG" },
  "+421": { name: "Slovakia", code: "SK" },
  "+386": { name: "Slovenia", code: "SI" },
  "+677": { name: "Solomon Islands", code: "SB" },
  "+252": { name: "Somalia", code: "SO" },
  "+27": { name: "South Africa", code: "ZA" },
  "+500": { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  "+82": { name: "South Korea", code: "KR" },
  "+211": { name: "South Sudan", code: "SS" },
  "+34": { name: "Spain", code: "ES" },
  "+94": { name: "Sri Lanka", code: "LK" },
  "+249": { name: "Sudan", code: "SD" },
  "+597": { name: "Suriname", code: "SR" },
  "+268": { name: "Eswatini", code: "SZ" },
  "+46": { name: "Sweden", code: "SE" },
  "+41": { name: "Switzerland", code: "CH" },
  "+963": { name: "Syria", code: "SY" },
  "+886": { name: "Taiwan", code: "TW" },
  "+992": { name: "Tajikistan", code: "TJ" },
  "+255": { name: "Tanzania", code: "TZ" },
  "+66": { name: "Thailand", code: "TH" },
  "+228": { name: "Togo", code: "TG" },
  "+690": { name: "Tokelau", code: "TK" },
  "+676": { name: "Tonga", code: "TO" },
  "+216": { name: "Tunisia", code: "TN" },
  "+90": { name: "Turkey", code: "TR" },
  "+993": { name: "Turkmenistan", code: "TM" },
  "+688": { name: "Tuvalu", code: "TV" },
  "+256": { name: "Uganda", code: "UG" },
  "+380": { name: "Ukraine", code: "UA" },
  "+971": { name: "United Arab Emirates", code: "AE" },
  "+598": { name: "Uruguay", code: "UY" },
  "+998": { name: "Uzbekistan", code: "UZ" },
  "+678": { name: "Vanuatu", code: "VU" },
  "+58": { name: "Venezuela", code: "VE" },
  "+84": { name: "Vietnam", code: "VN" },
  "+681": { name: "Wallis and Futuna", code: "WF" },
  "+967": { name: "Yemen", code: "YE" },
  "+260": { name: "Zambia", code: "ZM" },
  "+263": { name: "Zimbabwe", code: "ZW" },
  "+93": { name: "Afghanistan", code: "ITU" },
  // Add more countries as needed
};
